### ISSUE TITLE
Could you support copy to markdown?

### ISSUE THREAD

**Issue by ivysrono** [takedajs/TitleUrlCopy#5]
```
[title](url)
```

**Comment by takedajs** [comment]
@ivysrono 
Thank you for the issue!
We will consider introducing it when upgrading in the future!

**Comment by xavortm** [comment]
yes yes please! The thing I am searching the most of here is to be able to copy and paste directly a complete link. That would be:

copy -> paste -> result:
HTML link directly in the editor so that I can click it. When it's not in the rich editor, paste in markdown format. There is chrome extension that does this, I really want to see it here ^^ Didn't add new issue as it's practically the same thing

**Comment by networm** [comment]
I think you should consider use another addon and keep this addon simple.

The follow addon could use in Chrome and Firefox. I have used it for half a year.
[chitsaou/copy-as-markdown: Copying Link, Image and Tab(s) as Markdown Much Easier.](https://github.com/chitsaou/copy-as-markdown)

**Comment by takedajs** [comment]
@networm I also believe that the functionality of this add-on should be simple.

**Comment by takedajs** [comment]
@ivysrono @xavortm
Sorry to have kept you waiting. Implemented to select option and copy it in markdown format!

format
```
[title](url "title")
```
example
```
[Could you support copy to markdown? · Issue #5 · takedajs/TitleUrlCopy](https://github.com/takedajs/TitleUrlCopy/issues/5"Could you support copy to markdown? · Issue #5 · takedajs/TitleUrlCopy")

[TitleUrlCopy :: Versions :: Firefox向けアドオン](https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/versions/?page=1#version-1.4.0"TitleUrlCopy :: Versions :: Firefox向けアドオン")
```
https://addons.mozilla.org/ja/firefox/addon/titleurlcopy/versions/?page=1#version-1.4.0
